_homepage:
    pattern:  /
    defaults: { _controller: SensioHangmanBundle:User:registration }

security_check:
    pattern:  /auth

login:
    pattern:  /login
    defaults: { _controller: SensioHangmanBundle:User:login }

logout:
    pattern:  /logout

SensioHangmanBundle:
    resource: "@SensioHangmanBundle/Controller/"
    type:     annotation
    prefix:   /game

# Internal routing configuration to handle ESI
_internal:
   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
   prefix:   /_internal
