security:
    encoders:
        Sensio\Bundle\HangmanBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: true
            iterations: 3000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        players:
            entity: { class: SensioHangmanBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        game:
            pattern:                 ^/
            anonymous:               true
            form_login:    
                login_path:          /login
                check_path:          /auth
                default_target_path: /game/hangman/
            logout:
                path:                /logout
                target:              /login

    access_control:
        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/(login|registration)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(auth|logout)$, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/game/hangman, roles: [ ROLE_PLAYER ] }
        - { path: ^/game, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
